### ISSUE TITLE
Angular app not detected

### ISSUE THREAD

**Issue by dvinubius** [typebytes/angular-change-detection-tool#4]
With my Angular 8.2.8 app running, the extension says

This page doesn't appear to be using Angular.

In my Dev Tools, Ng Profiler section, I see the message:

Please trigger a CD cycle

**Comment by KwintenP** [comment]
Hey, 

Do you have Ivy enabled in the `angularCompilerOptions` in your `tsconfig.app.json ` file?

```
 "angularCompilerOptions": {
    "enableIvy": true
 }
```

**Comment by Rebaiahmed** [comment]
Hey @KwintenP does still apply with Angular14?

**Comment by KwintenP** [comment]
Nope it does not. This has been unmaintained for a while now and I have no intention of reviving it.
