### ISSUE TITLE
Angular 9 support

### ISSUE THREAD

**Issue by pwilkowski** [typebytes/angular-change-detection-tool#5]
Are you planning to update profiler to support angular 9 and ivy apps?

**Comment by KwintenP** [comment]
Yes!

It should work with Angular 8 + Ivy but I also noticed that it breaks under the RC versions of Angular 9. There are two reasons why it will take a month or so to update this.
- Angular is still changing there internal implementations quite often. This lib hooks into really low level API's and I don't want to change the implementation all the time :). As soon as Angular 9 is out, I'll work on the changes.
- I just don't have time the next 2 weeks :(

But it will for sure be updated!
