### ISSUE TITLE
ERROR RangeError: Maximum call stack size exceeded in all documentation pages

### ISSUE THREAD

**Issue by tobiashoeft** [typebytes/angular-change-detection-tool#6]
I got an error while browsing the documentation site on https://material.angular.io/

Releated to  https://github.com/angular/components/issues/18410

Only for history :-) i now it's an alpha ;) 

Thx

**Comment by KwintenP** [comment]
Yeah, the implementation totally breaks on the newer versions. Best to disable the extension for now. 
I'm trying to get it updated to angular 9 right now. I hope to be able to release a somewhat more stable version in the next month.

Problem is that between the first implementation and ng9 they changed the internal implementation quite often which also kills the extension.
